package load;

import model.LTS;
import model.RequestT;
import model.ResponseT;
import model.State;
import model.Transition;

/**
 * @author Elliott Blot
 * 
 */
public class DotLoader implements Loader {

	
	/**
	 * parse the dot received, and built the LTS that will be used by the mock.
	 */
	@Override
	public LTS load(String str) {
		LTS lts = new LTS();
		
		str = str.substring(29);
		if (str.startsWith(";")) {
			str = str.substring(1);
		}
		str = str.replace("S00 -> S1", "S00 -> S1[];");
		str = str.replace("S00 -> S1;", "S00 -> S1[];");
		String[] dot = str.split("];");
		int i = 0;			
		String line = dot[i] + "]";
		//TODO clean this step
		while (!line.startsWith("}")){
			// build the states
			if (line.contains("shape=circle")) { // it is the case if generated by CkTail
				String statename = line.substring(0, line.indexOf("["));
				State state = new State(statename);
				lts.addState(state);
			}
			// build the final states
			else if (line.contains("shape=doublecircle")) { // final state, not needed if generated by CkTail (loop)
				String statename = line.substring(0, line.indexOf("["));
				State state = new State(statename);
				state.setFinal();
				lts.addState(state);
			}
			// build the transitions
			else if (line.contains("->") & !line.contains("S00")) {
				String keySource = line.substring(0, line.indexOf(" ->"));
				String keyTarget = line.substring(line.indexOf(" ->")+4, line.indexOf("["));
				State source = lts.getState(keySource);
				State target = lts.getState(keyTarget);
				String trname = line.substring(line.indexOf("label =")+8, line.length() -1);
				Transition transition;
				if (trname.contains("status=")) { // TODO find a better method to differentiate responses and requests
					transition = new ResponseT(source, trname, target);
				}
				else{
					transition = new RequestT(source, trname, target);
				}
				lts.addTransition(transition);
				source.addSuccesseur(transition);
				target.addPredecesseur(transition);
			}
			// build initial state
			else if (line.contains("->") & line.contains("S00")) {
				String init = "";
				if (line.contains("[")) {
					init = line.substring(line.indexOf(" ->")+4, line.indexOf("["));
				}
				else {
					init = line.substring(line.indexOf(" ->")+4);
				}
				lts.setInitialState(lts.getState(init));
			}
			i++;
			line = dot[i];
		}
		lts.buildResp();
		return lts;
	}

}
